version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  app:
    build: .
    depends_on:
      - ollama
    volumes:
      - .:/app

volumes:
  ollama_data: